language: scala

env:
  - AWS_IPRANGE_LOCATION=https://ip-ranges.amazonaws.com/ip-ranges.json IS_HOSTED_BY_ASSETS_LOCATION=https://assets.is-hosted-by.com/ IPRANGES_LOCATION=https://ip-ranges.is-hosted-by.com/

script:
  - sbt test
  - sbt run &> /dev/null & 
  - cd load-test
  - sbt test
